#!/usr/bin/env bash

# Install aur packages
# Install Zen
wget https://aur.archlinux.org/cgit/aur.git/snapshot/zen-browser-bin.tar.gz -P /tmp/
cd /tmp
tar zxvf zen-browser-bin.tar.gz
cd zen-browser-bin
makepkg -sri
