#!/usr/bin/env bash

# Create common directories
mkdir $HOME/screenshots
mkdir $HOME/screenrecordings
mkdir $HOME/.config/personal
mkdir $HOME/.local/apps
mkdir $HOME/.local/scripts
mkdir $HOME/.local/bin
mkdir $HOME/.local/apps/
mkdir $HOME/.local/go/bin
mkdir /usr/local/go/bin
mkdir $HOME/.cargo/bin
