#!/usr/bin/env bash

# Install nodejs and npm with pacman

sudo pacman -Syy
sudo pacman -S nodejs npm
npm config set prefix ~/.local/npm
npm i -g n
n lts

# Install deno and bun
curl -fsSL https://deno.land/install.sh | sh
curl -fsSL https://bun.sh/install | bash
