#!/usr/bin/env bash

# Installed via pre-built tar file
#

#sudo pacman -Syy
#sudo pacman -S cmake clang lld llvm
wget https://ziglang.org/download/0.14.0/zig-0.14.0.tar.xz -P $HOME/personal/software_sources/zig_source

cd $HOME/personal/software_sources/zig_source
mkdir $HOME/.local/zig
tar xvf zig-0.14.0.tar.xz -C $HOME/personal/software_sources/
cd $HOME/personal/software_sources/zig-0.14.0
mkdir build
cd $HOME/personal/software_sources/zig-0.14.0/build
cmake ..
make install
mkdir $HOME/.local/zig
cp stage3/bin/zig $HOME/.local/zig/zig
