
[font]
size = 10.0

[font.bold]
family = "Inconsolata Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Inconsolata Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Inconsolata Nerd Font"
style = "Italic"

[font.normal]
family = "Inconsolata Nerd Font"
style = "Regular"

[window]
opacity = 0.6

[general]
import = ["/home/emilan/.config/alacritty/themes/kanagawa_dragon.toml"]
